---
version: '3'
services:
  synology-exporter:
    image: paranerd/synology-exporter
    container_name: synology-exporter
    restart: unless-stopped
    ports:
      - 9102:80
    volumes:
      ./targets.json:/app/targets.json
